version: "3.7"
services:
  pg-docker:
    image: postgres:14-alpine
    container_name: postgresql-dev
    environment:
      POSTGRES_DB: vidamaterna
      POSTGRES_PASSWORD: root
    ports:
      - "5445:5432"
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data
    networks:
      - dev-network
  pgadmin-docker:
    image: dpage/pgadmin4
    container_name: pgadmin-dev
    environment:
      PGADMIN_DEFAULT_EMAIL: vidamaterna@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    depends_on:
      - pg-docker
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge